name: ps3
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - glum
  - pandas
  - scikit-learn
  - lightgbm
  - ydata-profiling
  - pytest[version='>=6']
  - python[version='>=3.8']
  - pytest-cov
  - setuptools-scm
  - ipykernel
  - pre-commit
  - dask-ml
  - numpy[version='<2']
  - matplotlib
  - pip
  - huggingface_hub
  - dalex
  - nbformat
prefix: /Users/lsahar/miniconda3/envs/ps3
